services:
  - type: web
    name: kasrah-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kasrah-database
          property: connectionString
      - key: ADMIN_USERNAME
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: kasrah-database
    databaseName: kasrah
    user: kasrah_user